import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          type="module"
          // for local testing
          // src="http://localhost:5500/microfrontend-module/dist/bundle.js"

          //  npm published bundle
          // src="https://unpkg.com/@siddant-rachha/blog-components/dist/bundle.js"
          src="https://cdn.jsdelivr.net/npm/@siddant-rachha/blog-components/dist/bundle.js"
        ></Script>
      </head>
      <body>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  );
}
